title: Hello Universe and whoever may be out there!
author: Jayce Liu
email: jaycewu@online.nl
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Virtual reality and Mixed Reality are awesome.

# social links
twitter_username: NoTime4Twitter
github_username:  Jayce4dev

show_excerpts: true
